//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanDongHo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoAnPM_LTEntities : DbContext
    {
        public DoAnPM_LTEntities()
            : base("name=DoAnPM_LTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CTDonHang> CTDonHang { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<DonHang> DonHang { get; set; }
        public virtual DbSet<Favorite> Favorite { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ThongKe> ThongKe { get; set; }
    }
}
