//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanDongHo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CTDonHang = new HashSet<CTDonHang>();
            this.Favorite = new HashSet<Favorite>();
            this.ThongKe = new HashSet<ThongKe>();
        }
    
        public int IDSanpham { get; set; }
        public Nullable<int> IDPhanloai { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> TongSoLuong { get; set; }
        public Nullable<double> GiaBanDau { get; set; }
        public Nullable<double> GiaSP { get; set; }
        public string AnhMinhHoa { get; set; }
        public string AnhMinhHoa1 { get; set; }
        public string AnhMoTa1 { get; set; }
        public string AnhMoTa2 { get; set; }
        public string AnhMoTa3 { get; set; }
        public string AnhMoTa6 { get; set; }
        public string MoTaSP { get; set; }
        public string LoaiMay { get; set; }
        public string DuongKinh { get; set; }
        public string Mau { get; set; }
        public string ChatLieuDay { get; set; }
        public string DoChiuNuoc { get; set; }
        public string DoDay { get; set; }
        public string Size { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonHang> CTDonHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongKe> ThongKe { get; set; }
    }
}
